# CA 1 Cleansing


In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)

df = pd.read_csv(r'D:\NUS_TERM2_CA1\application_train.csv')
df.head(10)

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   
5      100008       0         Cash loans           M            N   
6      100009       0         Cash loans           F            Y   
7      100010       0         Cash loans           M            Y   
8      100011       0         Cash loans           F            N   
9      100012       0    Revolving loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   
5               Y             0           99000.0    490495.5      27517.5   
6               Y             1          171000.0   1560726.0      41301.0   
7               Y             0          360000.0   1530000.0      42075.0   
8               Y             0          112500.0   1019610.0      33826.5   
9               Y             0          135000.0    405000.0      20250.0   

   AMT_GOODS_PRICE  NAME_TYPE_SUITE      NAME_INCOME_TYPE  \
0         351000.0    Unaccompanied               Working   
1        1129500.0           Family         State servant   
2         135000.0    Unaccompanied               Working   
3         297000.0    Unaccompanied               Working   
4         513000.0    Unaccompanied               Working   
5         454500.0  Spouse, partner         State servant   
6        1395000.0    Unaccompanied  Commercial associate   
7        1530000.0    Unaccompanied         State servant   
8         913500.0         Children             Pensioner   
9         405000.0    Unaccompanied               Working   

             NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  \
0  Secondary / secondary special  Single / not married  House / apartment   
1               Higher education               Married  House / apartment   
2  Secondary / secondary special  Single / not married  House / apartment   
3  Secondary / secondary special        Civil marriage  House / apartment   
4  Secondary / secondary special  Single / not married  House / apartment   
5  Secondary / secondary special               Married  House / apartment   
6               Higher education               Married  House / apartment   
7               Higher education               Married  House / apartment   
8  Secondary / secondary special               Married  House / apartment   
9  Secondary / secondary special  Single / not married  House / apartment   

   REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  \
0                    0.018801       -9461           -637            -3648.0   
1                    0.003541      -16765          -1188            -1186.0   
2                    0.010032      -19046           -225            -4260.0   
3                    0.008019      -19005          -3039            -9833.0   
4                    0.028663      -19932          -3038            -4311.0   
5                    0.035792      -16941          -1588            -4970.0   
6                    0.035792      -13778          -3130            -1213.0   
7                    0.003122      -18850           -449            -4597.0   
8                    0.018634      -20099         365243            -7427.0   
9                    0.019689      -14469          -2019           -14437.

In [2]:

df.dropna(thresh=len(df) * 0.7, axis=1, inplace=True)
df.drop(['SK_ID_CURR'], axis=1, inplace=True)
df.shape

(307511, 71)

In [3]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le_count = 0

# Iterate through the columns
for col in df:
    if df[col].dtype == 'object':

        if len(list(df[col].unique())) <= 2:
            le.fit(df[col])
            df[col] = le.transform(df[col])

            le_count += 1
            
print('%d columns were label encoded.' % le_count)


3 columns were label encoded.


In [4]:
df = pd.get_dummies(df)
df.shape


(307511, 163)

In [5]:
null_columns = df.columns[df.isnull().any()]
for null_column in null_columns:
    df[null_column] = df[null_column].fillna(df[null_column].mean())

null_columns = df.columns[df.isnull().any()]
print(df[null_columns].isnull().sum())


Series([], dtype: float64)


In [6]:
import numpy as np
df['AMT_INCOME_TOTAL_LOG'] = np.log(df['AMT_INCOME_TOTAL'])
df['AMT_CREDIT_LOG'] = np.log(df['AMT_CREDIT'])
df['AMT_ANNUITY_LOG'] = np.log(df['AMT_ANNUITY'])
df['AMT_GOODS_PRICE_LOG'] = np.log(df['AMT_GOODS_PRICE'])
df.drop(['AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE'], axis=1,inplace = True)


In [7]:
df['YEARS_BIRTH_LOG'] = np.log(df['DAYS_BIRTH'].abs()/365)
df.loc[df.DAYS_EMPLOYED >= 0, 'DAYS_EMPLOYED'] = np.NaN 
df['DAYS_EMPLOYED'] = df['DAYS_EMPLOYED'].fillna(df['DAYS_EMPLOYED'].mean())
df['YEARS_EMPLOYED_LOG'] = np.log(df['DAYS_EMPLOYED'].abs()/365)

df.loc[df.DAYS_REGISTRATION >= 0, 'DAYS_REGISTRATION'] = np.NaN 
df['DAYS_REGISTRATION'] = df['DAYS_REGISTRATION'].fillna(df['DAYS_REGISTRATION'].mean())
df['YEARS_REGISTRATION_LOG'] = np.log(df['DAYS_REGISTRATION'].abs()/365)

df.loc[df.DAYS_ID_PUBLISH >= 0, 'DAYS_ID_PUBLISH'] = np.NaN 
df['DAYS_ID_PUBLISH'] = df['DAYS_ID_PUBLISH'].fillna(df['DAYS_ID_PUBLISH'].mean())
df['YEARS_ID_PUBLISH_LOG'] = np.log(df['DAYS_ID_PUBLISH'].abs()/365)

df.loc[df.DAYS_LAST_PHONE_CHANGE >= 0, 'DAYS_LAST_PHONE_CHANGE'] = np.NaN 
df['DAYS_LAST_PHONE_CHANGE'] = df['DAYS_LAST_PHONE_CHANGE'].fillna(df['DAYS_LAST_PHONE_CHANGE'].mean())
df['YEARS_LAST_PHONE_CHANGE_LOG'] = np.log(df['DAYS_LAST_PHONE_CHANGE'].abs()/365)

df.drop(['DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE'], axis=1,inplace = True)


In [8]:
y = df['TARGET']
X = df.drop('TARGET', axis=1)

from sklearn.model_selection import train_test_split, cross_val_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1 / 4, random_state=42)
# if stratify as true, train set is (7164, 48), test set is (5379, 48)

print(X_train.shape)

print(X_test.shape)       


(230633, 162)
(76878, 162)


In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [18]:
# imports 
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler

# random oversampling
# ros = RandomOverSampler(random_state=0)
ros = SMOTE(ratio='auto', kind='regular')
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# using Counter to display results of naive oversampling
from collections import Counter
print(sorted(Counter(y_resampled).items()))


u_ros = RandomUnderSampler(random_state=0)
# X_under_resampled, y_under_resampled = u_ros.fit_resample(X_train, y_train)
X_resampled, y_resampled = u_ros.fit_resample(X_train, y_train)

# using Counter to display results of naive oversampling
from collections import Counter
print(sorted(Counter(y_resampled).items()))

# print(sorted(Counter(y_under_resampled).items()))

#https://machinelearningmastery.com/data-preparation-gradient-boosting-xgboost-python/

[(0, 211999), (1, 211999)]
[(0, 18634), (1, 18634)]


In [19]:
#Option 1: Logistic regression
benchmark_cols = ['Variance retained','n_Components','Time(s)','Accuracy_percentage']
benchmark = pd.DataFrame(columns = benchmark_cols)


In [20]:
print('#Option 1: log reg')
from sklearn.linear_model import LogisticRegression
import time
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

variance = 1.0
n_components = X_train.shape[1]
logisticRegr = LogisticRegression(solver = 'saga', penalty='l1', class_weight='balanced', max_iter=1000)
start = time.time()
logisticRegr.fit(X_train, y_train)
end =  time.time()
timing = end-start
# Predict at Once
predicted = logisticRegr.predict(X_test)
print(logisticRegr)
# generate evaluation metrics
accuracy = (metrics.accuracy_score(y_test, predicted))
a = dict(zip(benchmark_cols,[variance,n_components,timing,accuracy]))
benchmark = benchmark.append(a,ignore_index=True)

print(benchmark)
print(confusion_matrix(y_test, predicted))
print(classification_report(y_test, predicted))


#Option 2: xgboost
print('Option 2: xgboost')
import xgboost as xgboost
import time

print('#Option 2: xgboost')
model = xgboost.XGBClassifier()
start = time.time()
model.fit(X_resampled, y_resampled)
end =  time.time()
timing = end-start
print(str(timing))
print(model)
# make predictions for test data
y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


#Option 3: Neural Network
print('Option 3: Neural Network')
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(solver='lbfgs', max_iter=1500, alpha=1e-4, hidden_layer_sizes=(120, 30, 30), learning_rate_init=.1)
# mlp = MLPClassifier(solver='sgd', activation='relu',alpha=1e-4,hidden_layer_sizes=(50, 50,50), random_state=1,max_iter=1000,verbose=10,learning_rate_init=.1)

mlp.fit(X_resampled, y_resampled)

print("Training set score: {:.3f}".format(mlp.score(X_resampled, y_resampled)))
print("Test set score: {:.3f}".format(mlp.score(X_test, y_test)))

from sklearn.metrics import confusion_matrix, classification_report

# Confusion Matrix
y_pred = mlp.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


#Option 4: Random Forest
print('#Option 4: Random Forest')
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(random_state=0)
rfc.fit(X_resampled, y_resampled)

y_train_pred = rfc.predict(X_resampled)
y_pred = rfc.predict(X_test)
rfc_proba = rfc.predict_proba(X_test)[:, 1]

print('classification_report - training:\n', classification_report(y_resampled, y_train_pred))
print('-' * 30)
print('classification_report - testing:\n',classification_report(y_test, y_pred))


#Option 5: Gradient Boost
print('#Option 5: Gradient Boost')
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(random_state=0)

gbc.fit(X_resampled, y_resampled)
y_train_pred = gbc.predict(X_resampled)
y_pred = gbc.predict(X_test)
gbc_proba = gbc.predict_proba(X_test)[:, 1]

print('classification_report - training:\n', classification_report(y_resampled, y_train_pred))
print('-' * 30)
print('classification_report - testing:\n',classification_report(y_test, y_pred))



#Option 1: log reg
LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=1000, multi_class='warn', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)
   Variance retained  n_Components     Time(s)  Accuracy_percentage
0                1.0         162.0  491.930364             0.685437
[[48546 22141]
 [ 2042  4149]]
              precision    recall  f1-score   support

           0       0.96      0.69      0.80     70687
           1       0.16      0.67      0.26      6191

    accuracy                           0.69     76878
   macro avg       0.56      0.68      0.53     76878
weighted avg       0.90      0.69      0.76     76878

Option 2: xgboost
#Option 2: xgboost
16.25124454498291
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=

c:\users\guofe\workspace\nus_is_pr\venv\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [12]:
from sklearn.decomposition import PCA
variance_list = [0.95,0.90,0.85,0.80,0.75,0.70, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]

def benchmark_pca(variance,train_img,train_lbl,test_img,test_lbl):
    global benchmark
    print(train_img.shape)
    pca = PCA(variance)
    pca.fit(train_img)
    n_components = pca.n_components_
    train_img = pca.transform(train_img)
    # pca.fit(test_img)
    test_img = pca.transform(test_img)
    logisticRegr = LogisticRegression(solver = 'saga', class_weight='balanced') #lbfgs seems not working, saga also not working
    start = time.time()
    logisticRegr.fit(train_img, train_lbl)
    end =  time.time()
 
    timing = end-start   
    # Predict for Multiple Observations (images) at Once
    predicted = logisticRegr.predict(test_img)   
    # generate evaluation metrics
    accuracy = (metrics.accuracy_score(test_lbl, predicted))
    #return 
    a = dict(zip(benchmark_cols,[variance,n_components,timing,accuracy]))
    benchmark = benchmark.append(a,ignore_index=True)
    
    
    print(confusion_matrix(test_lbl, predicted))
    print(classification_report(test_lbl, predicted))

    
for variance in variance_list:
    benchmark_pca(variance,X_train,y_train,X_test,y_test)
    
    



(230633, 162)
[[48192 22495]
 [ 2055  4136]]
              precision    recall  f1-score   support

           0       0.96      0.68      0.80     70687
           1       0.16      0.67      0.25      6191

    accuracy                           0.68     76878
   macro avg       0.56      0.67      0.52     76878
weighted avg       0.89      0.68      0.75     76878

(230633, 162)
[[47791 22896]
 [ 2088  4103]]
              precision    recall  f1-score   support

           0       0.96      0.68      0.79     70687
           1       0.15      0.66      0.25      6191

    accuracy                           0.68     76878
   macro avg       0.56      0.67      0.52     76878
weighted avg       0.89      0.68      0.75     76878

(230633, 162)
[[47533 23154]
 [ 2137  4054]]
              precision    recall  f1-score   support

           0       0.96      0.67      0.79     70687
           1       0.15      0.65      0.24      6191

    accuracy                           0.67    

c:\users\guofe\workspace\nus_is_pr\venv\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
c:\users\guofe\workspace\nus_is_pr\venv\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
c:\users\guofe\workspace\nus_is_pr\venv\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
c:\users\guofe\workspace\nus_is_pr\venv\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
c:\users\guofe\workspace\nus_is_pr\venv\lib\site-packages\sklearn\linear_model\sag.py:337: C